In [1]:
import numpy as np
import sys
from numpy.core.fromnumeric import shape, size
from random import seed
from random import random

In [2]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def Loss(Y, Y_predicted):
    return(sum(np.square(Y - Y_predicted))/Y.size)

In [3]:
def rand(size):
    rando=[]
    for i in range(size):
        rando.append(random())
        i+=1
    return rando

In [4]:
class Neroun:
    Outj=0
    Net=0
    weight=0
    bais=0
    delta=0
    def __init__(self, length, argv):
        print(argv)
        self.weight = np.array(argv)
        print("H", self.weight)
        # self.weight =rand(length)
        # self.bais = rand(1)

    def feedForward(self, inputs):
        print("H", inputs)
        self.Net= np.dot(np.array([self.weight]), np.transpose(np.array([inputs])))

        #print(self.Net)
        self.Outj = sigmoid(self.Net)
        return self.Outj
        
    def fit(self, eta, target, Outi):
        print(eta, target, Outi)
        self.delta=(target-self.Outj)*self.Outj*(1-self.Outj)
        print("I'm delta", self.delta)
        dw = eta*self.delta*Outi
        self.weight = self.weight + dw 
        print(dw)

In [5]:
class Layer:
    neurons =0
    output=0
    delta=0
    outputs=0
    def __init__(self, neuronNumber,length, weight):
        self.neurons = []
        for i in range(neuronNumber):
            neuron = Neroun(length, weight[i])
            self.neurons.append(neuron)
    
    def feedForward(self, inputs):
        self.inputs = inputs
        self.outputs =[]
        for i in range(len(self.neurons)):
            self.outputs.append(self.neurons[i].feedForward(inputs))
        return self.outputs
    
    def fit(self, eta, target, outj):
        # #self.neurons[len(self.neurons)-1].fit(eta, target, self.neurons[len(self.neurons)-2].Outj)
        # for i in range(len(self.neurons)-2, -1, -1):
        #     self.neurons[i].fit(eta, target,  self.neurons[len(self.neurons)-2].Outj)
        for i in range(len(self.neurons)):
           self.neurons[i].fit(eta, target[i], outj)
        


In [6]:
class Network:
    layers = 0
    layernum=0
    length=0
    inputs =0
    target =0
    def __init__(self, NumNeuron, inputs, target, *argv):
        self.layers = []
        self.inputs =inputs
        self.target = target
        length = len(inputs)
        for i in range (len(NumNeuron)):
            layer = Layer(NumNeuron[i], length, argv[i])  
            length = NumNeuron[i]   
            self.layers.append(layer)
    
    def feedForward(self):
        for i in range(len(self.layers)):
            self.inputs = self.layers[i].feedForward(self.inputs)
        return self.inputs
    
    def fit(self, eta):
        #delta=self.layers[len(self.layers)-1].fitFinal()
        #for i in range(len(self.layers)-1, -1, -1):
            self.layers[1].fit(eta, self.target, self.layers[0].outputs)



In [7]:
L1=np.array([[0.1, 0.4],[0.2, 0.5],[0.3, 0.6]])
L2 = np.array([[0.3, 0.4, 0.5], [0.3, 0.4, 0.5]])


In [8]:
L1[1]

array([0.2, 0.5])

In [9]:
Net = Network([3, 2], np.array([7, 4]), [0, 1], L1, L2)
#Net.fit(0.1)

[0.1 0.4]
H [0.1 0.4]
[0.2 0.5]
H [0.2 0.5]
[0.3 0.6]
H [0.3 0.6]
[0.3 0.4 0.5]
H [0.3 0.4 0.5]
[0.3 0.4 0.5]
H [0.3 0.4 0.5]


In [10]:
Net.feedForward()

H [7 4]
H [7 4]
H [7 4]
H [array([[0.90887704]]), array([[0.96770454]]), array([[0.98901306]])]
H [array([[0.90887704]]), array([[0.96770454]]), array([[0.98901306]])]


[array([[[[0.76028661]]]]), array([[[[0.76028661]]]])]

In [11]:
len([3, 5,2])

3

In [12]:
flmf=np.array([1])

In [13]:
Net.fit(5)

5 0 [array([[0.90887704]]), array([[0.96770454]]), array([[0.98901306]])]
I'm delta [[[[-0.13856291]]]]
[[[[-0.62968321]]

  [[-0.67043976]]

  [[-0.68520261]]]]
5 1 [array([[0.90887704]]), array([[0.96770454]]), array([[0.98901306]])]
I'm delta [[[[0.04368798]]]]
[[[[0.198535  ]]

  [[0.21138527]]

  [[0.2160399 ]]]]


In [14]:
Outj = np.array([0.76])
target = np.array([0])
eta = 5
Outi = np.array([0.909, 0.96, 0.989])


In [15]:
delta=(target-Outj)*Outj*(1-Outj)
print(delta)
dw = eta*delta*Outi
print(dw)


[-0.138624]
[-0.63004608 -0.6653952  -0.68549568]
