In [1]:
import numpy as np
import sys
from numpy.core.fromnumeric import shape, size
from random import seed
from random import random

In [2]:
def sigmoid(x):
  # Our activation function: f(x) = 1 / (1 + e^(-x))
  return 1 / (1 + np.exp(-x))

def Loss(Y, Y_predicted):
    return(sum(np.square(Y - Y_predicted))/Y.size)

In [3]:
def rand(size):
    rando=[]
    for i in range(size):
        rando.append(random())
        i+=1
    return rando

In [25]:
class Neroun:
    Out=0
    Net=0
    weight=0
    bais=0
    def __init__(self, length):
        print(length)
        self.weight =rand(length)
        self.bais = rand(1)

    def feedForward(self, inputs):
        self.Net= np.dot(np.array([self.weight]), np.transpose(np.array([inputs])))+self.bais
        print(self.Net)
        self.Out = sigmoid(self.Net)
        return self.Out 
        



In [5]:
class Layer:
    neurons =0
    output=0
    delta=0
    def __init__(self, neuronNumber,length):
        self.neurons = []
        for i in range(neuronNumber):
            neuron = Neroun(length)
            self.neurons.append(neuron)
    
    def feedForward(self, inputs):
        outputs =[]
        for i in range(len(self.neurons)):
            outputs.append(self.neurons[i].feedForward(inputs))
        return outputs


In [6]:
class Network:
    layers = 0
    layernum=0
    length=0
    def __init__(self, layerNmber, NumNeuron, length):
        self.layers = []
        for i in range (layerNmber):
            layer = Layer(NumNeuron[i], length)  
            length = NumNeuron[i]   
            self.layers.append(layer)
    
    def feedForward(self, inputs):
        for i in range(len(self.layers)):
            inputs = self.layers[i].feedForward(inputs)
        return inputs


In [7]:
Ne = Network(3, [2, 3, 2], 3)

3
3
2
2
2
3
3


In [8]:
print(Ne.layers[0].neurons[0].weight)



[0.8574250499177885, 0.0005381808286526457, 0.6861165300377393]


In [9]:
print(Ne.layers[1].neurons[0].weight)

[0.07593157121933214, 0.7372037783381323]


In [10]:
print(Ne.layers[2].neurons[0].weight)

[0.8509302820784624, 0.3614877500970004, 0.47418259241316385]


In [24]:
print(Ne.layers[0].neurons[0].weight)
print(Ne.layers[0].neurons[1].weight)
print(Ne.layers[1].neurons[0].weight)
print(Ne.layers[1].neurons[1].weight)
print(Ne.layers[1].neurons[2].weight)
print(Ne.layers[2].neurons[0].weight)
print(Ne.layers[2].neurons[1].weight)

[0.8574250499177885, 0.0005381808286526457, 0.6861165300377393]
[0.06206169799893324, 0.3625445748702094, 0.9224976280768732]
[0.07593157121933214, 0.7372037783381323]
[0.20311574982098368, 0.3879994818357003]
[0.42507195687228627, 0.49667353692725]
[0.8509302820784624, 0.3614877500970004, 0.47418259241316385]
[0.9100527387664562, 0.00934678151431012, 0.7460079838603515]


In [54]:
print(Ne.layers[0].neurons[0].bais)
print(Ne.layers[0].neurons[1].bais)
print(Ne.layers[1].neurons[0].bais)
print(Ne.layers[1].neurons[1].bais)
print(Ne.layers[1].neurons[2].bais)
print(Ne.layers[2].neurons[0].bais)
print(Ne.layers[2].neurons[1].bais)


[0.41497159243470183]
[0.339492479274098]
[0.7221050151121574]
[0.938374927729999]
[0.14121279900701433]
[0.1282062635217307]
[0.1993699638989268]


In [28]:
print(Ne.feedForward([0, 0, 0]))

[array([[[[[[0.79910813]]]]]]), array([[[[[[0.80253389]]]]]])]


In [ ]:



# generate random integer values
from numpy.random import seed
from numpy.random import randint

In [ ]:
num = rand(10)
print(num)

[0.7398985747399307, 0.922324996665417, 0.029005228283614737, 0.46562265437810535, 0.9433567169983137, 0.6489745531369242, 0.9009004917506227, 0.11320596465314436, 0.46906904778216374, 0.24657283261983032]


In [49]:
weight = [0.07593157121933214, 0.7372037783381323]
inputs = [0.6022793721906061, 0.5840672348179832]

sigmoid(np.dot(np.array([weight]), np.transpose(np.array([inputs])))+0.7221050151121574)

array([[0.76824245]])

In [48]:
out = sigmoid(0.339492479274098)
out

0.5840672348179832

In [47]:
weight = [0.20311574982098368, 0.3879994818357003]
inputs = [0.6022793721906061, 0.5840672348179832]

sigmoid(np.dot(np.array([weight]), np.transpose(np.array([inputs])))+0.938374927729999)

array([[0.7836941]])

In [46]:
weight = [0.42507195687228627, 0.49667353692725]
inputs = [0.6022793721906061, 0.5840672348179832]

sigmoid(np.dot(np.array([weight]), np.transpose(np.array([inputs])))+0.14121279900701433)

array([[0.6653695]])

array([[0.79910813]])

In [56]:

weight = [0.8509302820784624, 0.3614877500970004, 0.47418259241316385]
inputs = [0.76824245, 0.7836941, 0.6653695]

sigmoid(np.dot(np.array([weight]), np.transpose(np.array([inputs])))+0.1282062635217307)

array([[0.79910813]])

In [55]:

weight = [0.9100527387664562, 0.00934678151431012, 0.7460079838603515]
inputs = [0.76824245, 0.7836941, 0.6653695]

sigmoid(np.dot(np.array([weight]), np.transpose(np.array([inputs])))+0.1993699638989268)

array([[0.80253389]])

In [ ]:
a = [1, 5]

print(shape(a))
print()

(2,)
[[1]
 [5]]
