In [59]:
import numpy as np
import sys
from numpy.core.fromnumeric import shape, size
from random import seed
from random import random

In [60]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def Loss(Y, Y_predicted):
    return(sum(np.square(Y - Y_predicted))/Y.size).sum()

In [61]:
def rand(row, column):
    returned = np.empty((row, column))
    for j in range(row):
        rando=[]
        for i in range(column):
            rando.append(random())
            i+=1
        returned[j] = rando
    return returned

In [62]:
class Layer:
    nerweight =0
    inputs = 0
    outputs=[]
    delta=0

    def __init__(self, neuronNumber,length, weight):
        # self.nerweight = weight
        self.nerweight =rand(neuronNumber ,length)
        self.bais = rand(neuronNumber , 1)

    def feedForward(self, inputs):
        self.inputs = inputs
        self.outputs  = sigmoid(np.dot(np.array(self.nerweight), np.array(self.inputs)))
        return self.outputs 

    
    def fit(self, eta, target, outj, sumDelta):
        if(size(sumDelta)==0):
            # print ("OU",self.outputs)
            self.delta=(target-self.outputs)*self.outputs*(1-self.outputs)
            dw = eta*np.transpose([self.delta])*np.transpose(outj)
            self.nerweight = self.nerweight + dw 
            return np.dot(self.delta, self.nerweight)
        else:
            self.delta=sumDelta*self.outputs*(1-self.outputs)
            
            dw = eta*self.delta*np.transpose([outj])
            self.nerweight = self.nerweight + dw.reshape(3,2)
            
            

In [63]:
delta = []
if(size(delta)==0):
    print("hi")
else:
    print("Bye")

hi


In [64]:
class Network:
    layers = 0
    layernum=0
    length=0
    orin=0
    inputs =0
    target =0
    def __init__(self, NumNeuron, inputs, target, *argv):
        self.layers = []
        self.orin = inputs
        self.inputs =inputs
        self.target = target
        length = shape(inputs)[1]
        for i in range (len(NumNeuron)):
            layer = Layer(NumNeuron[i], length, argv[i])  
            length = NumNeuron[i]   
            self.layers.append(layer)
    def re (self):
        print(self.orin[0])
        
    def feedForward(self, datafeeded):
        current = self.inputs[datafeeded]
        for i in range(len(self.layers)):
            current= self.layers[i].feedForward(current)
        return current
    
    def fit(self, eta, leranRate):
        for j in range(leranRate):
            now = np.empty((shape(self.target)))
            for k in range((shape(self.orin)[0])):
                now[k] =self.feedForward(k)
                sumdelta = []
                for i in range(len(self.layers)-1, 0, -1):
                    sumdelta =self.layers[i].fit(eta, self.target[k], self.layers[i-1].outputs, sumdelta)
                sumdelta =self.layers[0].fit(eta, self.target[k], self.orin[k], sumdelta)
            print(Loss(now, self.target))

In [65]:
L1 = np.array([[0.1, 0.4],[0.2, 0.5],[0.3, 0.6]])
L2 = np.array([[0.3, 0.4, 0.5], [0.3, 0.4, 0.5]])


In [66]:
np.array([[7, 4,2],[2, 1,3]])

array([[7, 4, 2],
       [2, 1, 3]])

In [67]:
L1[1]

array([0.2, 0.5])

In [68]:
Net = Network([3, 2], np.array([[7, 4],[5, 1], [10, 2]]), np.array([[1, 0],[1, 0], [1, 0]]), L1, L2)
#Net.fit(0.1)

In [69]:
Net.re()

[7 4]


In [70]:
5*np.dot(np.transpose([[-0.13856291,  0.04368798]]), [[0.90887704, 0.96770454, 0.98901306]])

array([[-0.62968324, -0.67043979, -0.68520264],
       [ 0.19853501,  0.21138528,  0.21603991]])

In [71]:
#Loss(Net.feedForward(), [0, 1])

In [72]:
Net.fit(10,5)


0.1657029845914338
0.00234459705799411
0.0016090346324131814
0.0012410671647816898
0.0010148234905430313


In [73]:
o=np.array([0.90887704, 0.96770454, 0.98901306])
d = np.array([0.06746185, 0.0641831,  0.05694455])
np.transpose(d)*[o]*([1-o])

array([[0.00558716, 0.00200588, 0.00061877]])

In [74]:
Outj = np.array([0.76])
target = np.array([0])
eta = 5
Outi = np.array([0.909, 0.96, 0.989])


In [75]:
delta=(target-Outj)*Outj*(1-Outj)
print(delta)
dw = eta*delta*Outi
print(dw)


[-0.138624]
[-0.63004608 -0.6653952  -0.68549568]


In [76]:
l=np.array([[1,2,5],[5, 0.2, 3]])