In [1]:
import numpy as np
import sys
from numpy.core.fromnumeric import shape, size
from random import seed
from random import random

In [2]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def Loss(Y, Y_predicted):
    return(sum(np.square(Y - Y_predicted))/Y.size)

In [3]:
def rand(row, column):
    returned = np.empty((row, column))
    for j in range(row):
        rando=[]
        for i in range(column):
            rando.append(random())
            i+=1
        returned[j] = rando
    return returned

In [4]:
rand(5,1)

array([[0.64574262],
       [0.60752756],
       [0.33311581],
       [0.87787907],
       [0.26420473]])

In [6]:
nerweight = np.empty((2,3))

In [7]:
shape(nerweight)

(2, 3)

In [8]:
nerweight = ([1,2,8], [4, 7, 9])
nerweight

([1, 2, 8], [4, 7, 9])

In [9]:
outputs = np.dot(np.array([[1,5],[2,7], [10, 9]]), [[2],[3]])
outputs

array([[17],
       [25],
       [47]])

In [101]:
class Layer:
    nerweight =0
    inputs = 0
    outputs=[]
    delta=0

    def __init__(self, neuronNumber,length, weight):
        self.nerweight = weight
        #self.nerweight =rand(neuronNumber ,length)
        #self.bais = rand(neuronNumber , 1)

    def feedForward(self, inputs):
        self.inputs = inputs
        self.outputs  = sigmoid(np.dot(np.array(self.nerweight), np.array(self.inputs)))
        return self.outputs 

    
    def fit(self, eta, target, outj):
        #print(eta, target, Outj)
        self.delta=(target-self.outputs)*self.outputs*(1-self.outputs)
        # print("I'm delta", self.delta)
        print(eta, self.delta,outj)
        dw = eta*np.transpose([self.delta])*np.transpose(outj)
        print(dw, self.nerweight)
        self.nerweight = self.nerweight + dw 
        print(self.nerweight)
        # #self.neurons[len(self.neurons)-1].fit(eta, target, self.neurons[len(self.neurons)-2].Outj)
        # for i in range(len(self.neurons)-2, -1, -1):
        #     self.neurons[i].fit(eta, target,  self.neurons[len(self.neurons)-2].Outj)
        # for i in range(len(self.neurons)):
        #    self.neurons[i].fit(eta, target[i], outj)
        


In [32]:
class Network:
    layers = 0
    layernum=0
    length=0
    inputs =0
    target =0
    def __init__(self, NumNeuron, inputs, target, *argv):
        self.layers = []
        self.inputs =inputs
        self.target = target
        length = len(inputs)
        for i in range (len(NumNeuron)):
            layer = Layer(NumNeuron[i], length, argv[i])  
            length = NumNeuron[i]   
            self.layers.append(layer)
    
    def feedForward(self):
        for i in range(len(self.layers)):
            self.inputs = self.layers[i].feedForward(self.inputs)
        return self.inputs
    
    def fit(self, eta):
        #delta=self.layers[len(self.layers)-1].fitFinal()
        #for i in range(len(self.layers)-1, -1, -1):
            self.layers[1].fit(eta, self.target, self.layers[0].outputs)



In [12]:
L1=np.array([[0.1, 0.4],[0.2, 0.5],[0.3, 0.6]])
L2 = np.array([[0.3, 0.4, 0.5], [0.3, 0.4, 0.5]])


In [13]:
L1[1]

array([0.2, 0.5])

In [103]:
Net = Network([3, 2], np.array([7,4]), [0, 1], L1, L2)
#Net.fit(0.1)

In [86]:
5*np.dot(np.transpose([[-0.13856291,  0.04368798]]), [[0.90887704, 0.96770454, 0.98901306]])

array([[-0.62968324, -0.67043979, -0.68520264],
       [ 0.19853501,  0.21138528,  0.21603991]])

In [104]:
Net.feedForward()

array([0.76028661, 0.76028661])

In [16]:
len([3, 5,2])

3

In [17]:
flmf=np.array([1])

In [105]:
Net.fit(5)

5 [-0.13856291  0.04368798] [0.90887704 0.96770454 0.98901306]
[[-0.62968321 -0.67043976 -0.68520261]
 [ 0.198535    0.21138527  0.2160399 ]] [[0.3 0.4 0.5]
 [0.3 0.4 0.5]]
[[-0.32968321 -0.27043976 -0.18520261]
 [ 0.498535    0.61138527  0.7160399 ]]


In [ ]:
Outj = np.array([0.76])
target = np.array([0])
eta = 5
Outi = np.array([0.909, 0.96, 0.989])


In [ ]:
delta=(target-Outj)*Outj*(1-Outj)
print(delta)
dw = eta*delta*Outi
print(dw)


[-0.138624]
[-0.63004608 -0.6653952  -0.68549568]


In [ ]:
l=np.array([[1,2,5],[5, 0.2, 3]])