In [1]:
import numpy as np
import sys
from numpy.core.fromnumeric import shape, size
from random import seed
from random import random

In [2]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def Loss(Y, Y_predicted):
    return(sum(np.square(Y - Y_predicted))/Y.size)

In [3]:
def rand(row, column):
    returned = np.empty((row, column))
    for j in range(row):
        rando=[]
        for i in range(column):
            rando.append(random())
            i+=1
        returned[j] = rando
    return returned

In [4]:
class Layer:
    nerweight =0
    inputs = 0
    outputs=[]
    delta=0

    def __init__(self, neuronNumber,length, weight):
        #self.nerweight = weight
        self.nerweight =rand(neuronNumber ,length)
        self.bais = rand(neuronNumber , 1)

    def feedForward(self, inputs):
        self.inputs = inputs
        self.outputs  = sigmoid(np.dot(np.array(self.nerweight), np.array(self.inputs)))
        return self.outputs 

    
    def fit(self, eta, target, outj, sumDelta):
        if(size(sumDelta)==0):
            self.delta=(target-self.outputs)*self.outputs*(1-self.outputs)
            dw = eta*np.transpose([self.delta])*np.transpose(outj)
            self.nerweight = self.nerweight + dw 
            return np.dot(self.delta, self.nerweight)
        else:
            self.delta=sumDelta*self.outputs*(1-self.outputs)
            
            dw = eta*self.delta*np.transpose([outj])
            self.nerweight = self.nerweight + dw.reshape(3,2)
            
            

In [5]:
delta = []
if(size(delta)==0):
    print("hi")
else:
    print("Bye")

hi


In [6]:
class Network:
    layers = 0
    layernum=0
    length=0
    orin=0
    inputs =0
    target =0
    def __init__(self, NumNeuron, inputs, target, *argv):
        self.layers = []
        self.orin = inputs
        self.inputs =inputs
        self.target = target
        length = len(inputs)
        for i in range (len(NumNeuron)):
            layer = Layer(NumNeuron[i], length, argv[i])  
            length = NumNeuron[i]   
            self.layers.append(layer)
    
    def feedForward(self):
        for i in range(len(self.layers)):
            self.inputs = self.layers[i].feedForward(self.inputs)
        return self.inputs
    
    def fit(self, eta, leranRate):
        for j in range(leranRate):
            sumdelta = []
            for i in range(len(self.layers)-1, 0, -1):
                sumdelta =self.layers[i].fit(eta, self.target, self.layers[i-1].outputs, sumdelta)
            sumdelta =self.layers[0].fit(eta, self.target, self.orin, sumdelta)


In [7]:
L1 =np.array([[0.1, 0.4],[0.2, 0.5],[0.3, 0.6]])
L2 = np.array([[0.3, 0.4, 0.5], [0.3, 0.4, 0.5]])


In [8]:
L1[1]

array([0.2, 0.5])

In [9]:
Net = Network([3, 2], np.array([7,4]), [0, 1], L1, L2)
#Net.fit(0.1)

In [10]:
5*np.dot(np.transpose([[-0.13856291,  0.04368798]]), [[0.90887704, 0.96770454, 0.98901306]])

array([[-0.62968324, -0.67043979, -0.68520264],
       [ 0.19853501,  0.21138528,  0.21603991]])

In [11]:
Loss(Net.feedForward(), [0, 1])

0.3414024466672704

In [12]:
Net.fit(5,1)
print(Loss(Net.feedForward(), [0, 1]))
Net.fit(5,1)
print(Loss(Net.feedForward(), [0, 1]))
Net.fit(5,1)
print(Loss(Net.feedForward(), [0, 1]))

0.12034038443514282
0.04291471724508582
0.024477115667830382


In [13]:
o=np.array([0.90887704, 0.96770454, 0.98901306])
d = np.array([0.06746185, 0.0641831,  0.05694455])
np.transpose(d)*[o]*([1-o])

array([[0.00558716, 0.00200588, 0.00061877]])

In [14]:
Outj = np.array([0.76])
target = np.array([0])
eta = 5
Outi = np.array([0.909, 0.96, 0.989])


In [15]:
delta=(target-Outj)*Outj*(1-Outj)
print(delta)
dw = eta*delta*Outi
print(dw)


[-0.138624]
[-0.63004608 -0.6653952  -0.68549568]


In [16]:
l=np.array([[1,2,5],[5, 0.2, 3]])